apiVersion: v1
kind: Service
metadata:
  name: demo-backend
  labels:
    app: demo-backend
spec:
  selector:
    app: demo-backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
